using System;
using System.Collections.Generic;

namespace ColdChainX.Application.DTOs.WarehouseReceipt
{
    /// <summary>
    /// Response model representing a warehouse receipt.
    /// </summary>
    public class WarehouseReceiptResponse
    {
        /// <summary>
        /// Unique system identifier of the receipt.
        /// </summary>
        public Guid ReceiptId { get; set; }

        /// <summary>
        /// System-generated receipt business code.
        /// </summary>
        public string ReceiptCode { get; set; } = null!;

        /// <summary>
        /// Optional reference number of an external document (e.g. delivery note).
        /// </summary>
        public string? ReferenceDocNo { get; set; }

        /// <summary>
        /// Unique identifier of the associated transport order.
        /// </summary>
        public Guid OrderId { get; set; }

        /// <summary>
        /// Tracking code of the corresponding transport order.
        /// </summary>
        public string OrderTrackingCode { get; set; } = null!;

        /// <summary>
        /// Unique identifier of the destination warehouse.
        /// </summary>
        public Guid WarehouseId { get; set; }

        /// <summary>
        /// Name of the receiving warehouse.
        /// </summary>
        public string WarehouseName { get; set; } = null!;

        /// <summary>
        /// Type of receipt (e.g. StandardInbound).
        /// </summary>
        public string ReceiptType { get; set; } = null!;

        /// <summary>
        /// Optional reason notes.
        /// </summary>
        public string? Reason { get; set; }

        /// <summary>
        /// Total expected quantity of items based on the order.
        /// </summary>
        public decimal? TotalExpectedQty { get; set; }

        /// <summary>
        /// Total actual quantity recorded upon arrival.
        /// </summary>
        public decimal? TotalActualQty { get; set; }

        /// <summary>
        /// Quality control recorded temperature (Celsius) of the cargo environment on arrival.
        /// </summary>
        public decimal? RecordedTemperature { get; set; }

        /// <summary>
        /// Name of the driver/deliverer.
        /// </summary>
        public string DelivererName { get; set; } = null!;

        /// <summary>
        /// Unique identifier of the warehouse operator who received the cargo.
        /// </summary>
        public Guid ReceiverId { get; set; }

        /// <summary>
        /// Inbound notes.
        /// </summary>
        public string? Note { get; set; }

        /// <summary>
        /// URL path to the generated PDF receipt document.
        /// </summary>
        public string? PdfUrl { get; set; }

        /// <summary>
        /// Processing status of the receipt (e.g., DRAFT, QC_COMPLETED, COMPLETED).
        /// </summary>
        public string? Status { get; set; }

        /// <summary>
        /// Warn message generated by compliance rules (e.g., temperature deviation).
        /// </summary>
        public string? WarningMessage { get; set; }

        /// <summary>
        /// Timestamp when the receipt was created.
        /// </summary>
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// List of line items included in this receipt.
        /// </summary>
        public List<WarehouseReceiptItemDto> Items { get; set; } = new List<WarehouseReceiptItemDto>();
    }

    /// <summary>
    /// Line item detail of a warehouse receipt.
    /// </summary>
    public class WarehouseReceiptItemDto
    {
        /// <summary>
        /// Unique identifier of the receipt line item.
        /// </summary>
        public Guid ItemId { get; set; }

        /// <summary>
        /// Name of the received product.
        /// </summary>
        public string ItemName { get; set; } = null!;

        /// <summary>
        /// Unique code of the received product.
        /// </summary>
        public string? ItemCode { get; set; }

        /// <summary>
        /// Unit of measure.
        /// </summary>
        public string Unit { get; set; } = null!;

        /// <summary>
        /// Quantity expected from the transport order.
        /// </summary>
        public decimal ExpectedQty { get; set; }

        /// <summary>
        /// Actual quantity verified physically at receipt.
        /// </summary>
        public decimal ActualQty { get; set; }

        /// <summary>
        /// Actual weight in kilograms.
        /// </summary>
        public decimal? ActualWeightKg { get; set; }

        /// <summary>
        /// Verified packaging length in centimeters.
        /// </summary>
        public decimal? LengthCm { get; set; }

        /// <summary>
        /// Verified packaging width in centimeters.
        /// </summary>
        public decimal? WidthCm { get; set; }

        /// <summary>
        /// Verified packaging height in centimeters.
        /// </summary>
        public decimal? HeightCm { get; set; }

        /// <summary>
        /// Product barcode scanner value.
        /// </summary>
        public string? Barcode { get; set; }

        /// <summary>
        /// Product QR code scanner value.
        /// </summary>
        public string? QrCode { get; set; }

        /// <summary>
        /// Quality condition code (e.g., INTACT, LEAKING).
        /// </summary>
        public string? ConditionStatus { get; set; }

        /// <summary>
        /// Notes regarding the condition of this item.
        /// </summary>
        public string? Note { get; set; }

        /// <summary>
        /// Lot/Batch number of the product.
        /// </summary>
        public string? BatchNumber { get; set; }

        /// <summary>
        /// Date when this batch was manufactured.
        /// </summary>
        public DateOnly? ManufacturedDate { get; set; }

        /// <summary>
        /// Expiration date of the batch.
        /// </summary>
        public DateOnly? ExpiryDate { get; set; }
    }
}
